# Generated by Django 3.2.15 on 2023-05-28 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QrLibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='name',
            new_name='material_location',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='material_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='material_qty',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='material_special_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
