# Generated by Django 3.2.15 on 2023-05-28 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QrLibraryApp', '0003_remove_qrcode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='material_other',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
